title: Default
fields:
  -
    handle: content
    field:
      type: bard
      display: Content
      localizable: true
  -
    handle: template
    field:
      type: template
      display: Template
      localizable: true
